# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.CharField(help_text='Enter unique Police id', max_length=30, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
