# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171225_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='media.Media'),
            preserve_default=False,
        ),
    ]
