# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171225_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
