# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('witness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(blank=True, max_length=250)),
                ('location', models.CharField(max_length=200)),
                ('resolved', models.BooleanField(default=False)),
                ('witness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='witness.Witness')),
            ],
        ),
    ]
