# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time_created',
            field=models.DateTimeField(auto_created=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
