# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
