# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('witness', '0004_auto_20171215_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='witness',
            name='reports',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
    ]
