# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witness', '0005_auto_20171224_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='witness',
            name='reports',
        ),
    ]
