# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='report',
        ),
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
    ]
