# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20180106_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.CharField(blank=True, default=0, max_length=100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000),
            preserve_default=False,
        ),
    ]
