# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_media'),
        ('media', '0002_auto_20171225_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='reports.Report'),
        ),
    ]
