# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20180111_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='filename',
            field=models.CharField(default=34, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
