# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20171228_2037'),
        ('media', '0005_auto_20180112_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='reports.Report'),
        ),
    ]
